apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: demo-ns
  labels:
    app: rabbitmq
data:
  definitions.json: |
     {
      "users": [
        {
          "name": "guest",
          "password_hash": "R184F4Fs6JLdo8tFqRjWnkJL2DlAZJupxEqkO/8kfV/G63+z",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        },
        {
          "name": "admin",
          "password_hash": "6DaL6KEHjF/W4owXqjHlIj+olmY7qa1jpfErJpWe2hY8F9V4",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        },
        {
          "user": "admin",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "parameters": [],
      "policies": [],
      "queues": [],
      "exchanges": [],
      "bindings": []
     }
  rabbitmq.conf: |
         # Default user
          default_user = admin
          default_pass = 6DaL6KEHjF/W4owXqjHlIj+olmY7qa1jpfErJpWe2hY8F9V4

          ## The default "guest" user is only permitted to access the server
          ## via a loopback interface (e.g. localhost).
          loopback_users.guest = false

          # IPv4
          listeners.tcp.default = 5672

          ## HTTP listener and embedded Web server settings.
          #management.tcp.port = 15672

          # Load queue definitions
          management.load_definitions = /etc/rabbitmq/definitions.json

          #Ignore SSL
          ssl_options.verify               = verify_peer
          ssl_options.fail_if_no_peer_cert = false

          vm_memory_high_watermark.absolute = 3GB
  enabled_plugins: |
           [rabbitmq_management].