apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: demo-ns
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
    - name: rabbitmq-amqp
      port: 5672
      targetPort: 5672
  type: ClusterIP
