apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rabbitmq
  labels:
    app:  rabbitmq
  namespace: rabbit
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.7.6-management
        imagePullPolicy: Always
        name:  rabbitmq
        # envFrom:
        #   - configMapRef:
        #       name: rabbitmq-env
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        ports:
        - containerPort: 15672
          name: rabbitmq-port
        - containerPort: 5672
          name: rabbitmq-cli
        volumeMounts:
            - mountPath: /etc/rabbitmq/
              name: rabbit-conf
            - mountPath: /var/lib/rabbitmq
              name: standard
    
      volumes:
        - name: rabbit-conf
          configMap:
            name: rabbitmq-env
        - name: standard
          persistentVolumeClaim:
            claimName: data   

        
        
        