kind: Service
apiVersion: v1
metadata:
  name:  rabbitmq
  labels:
    app: rabbitmq
  namespace: rabbit
spec:
  selector:
    app:  rabbitmq
  ports:
    - name:  rabbitmq-port
      port:  5672
      targetPort: 5672

    - name:  rabbitmq-cli
      port:  15672
      targetPort: 15672