apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: data
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
      requests:
        storage: 50Mi
          