version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    deploy:
      resources:
        limits:
          cpus: '4' # Adjust the CPU limit as needed
          memory: 4g
        reservations:
          cpus: '4' # Adjust the CPU reservation as needed
          memory: 4g
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    restart: always
    image: docker.elastic.co/kibana/kibana:8.1.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge

