version: "2"
services:
  frontend-admin:
    build:
      context: './admin_static_build'
      dockerfile: Dockerfile
    container_name: frontend-admin
    restart: unless-stopped
    ports:
      - 7000:7000
