apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uat-explorer-backend
  namespace: nexablock-ns 
spec:
  secretStoreRef:
    name: uat-explorer
    kind: SecretStore  
  refreshInterval: "10s"
  target:
    name: uat-explorer-backend
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
  - extract:
      key: ADMIN_ADDRESS_KEY
