apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: uat-explorer
  namespace: nexablock-ns 
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    aws:
      service: SecretsManager
      region: us-east-1