apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
  namespace: fcbank-ns
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8099
      protocol: TCP
  selector:
    app: gateway
