apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-claim
  namespace: nexablock-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc
