apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pv-claim
  namespace: stage-demo 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc
