apiVersion: v1
kind: Service
metadata:
  name: php-admin
  #namespace: ingress  # Add the namespace field here
  labels:
    app: php-admin
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: '/'
spec:
  selector:
    app: php-admin
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
  type: ClusterIP
