apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: antier-platform
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka
  type: ClusterIP