apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: antier-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop
        ports:
        - containerPort: 9000
        env:
        - name: KAFKA_BROKERCONNECT
          value: kafka-service:9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
  namespace: antier-platform
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: kafdrop
